import { BoardTile } from './types';

export const BOARD_TILES: BoardTile[] = [
  {
    index: 0,
    label: 'Start',
    word: 'start',
    category: 'start',
    color: 'bg-emerald-500 border-emerald-600 text-white shadow-emerald-200',
    gridRow: 5,
    gridCol: 4,
    arrowDirection: 'left',
  },
  {
    index: 1,
    label: 'Book',
    word: 'book',
    category: 'school',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-900 shadow-yellow-100',
    gridRow: 5,
    gridCol: 3,
    arrowDirection: 'left',
  },
  {
    index: 2,
    label: '1',
    word: 'one',
    category: 'number',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-900 shadow-indigo-100',
    gridRow: 5,
    gridCol: 2,
    arrowDirection: 'left',
  },
  {
    index: 3,
    label: 'Computer Game',
    word: 'computer game',
    category: 'toy',
    color: 'bg-rose-100 border-rose-300 text-rose-900 shadow-rose-100',
    gridRow: 5,
    gridCol: 1,
    arrowDirection: 'left',
  },
  {
    index: 4,
    label: 'Pen',
    word: 'pen',
    category: 'school',
    color: 'bg-fuchsia-100 border-fuchsia-300 text-fuchsia-900 shadow-fuchsia-100',
    gridRow: 5,
    gridCol: 0,
    arrowDirection: 'up',
  },
  {
    index: 5,
    label: '10',
    word: 'ten',
    category: 'number',
    color: 'bg-sky-100 border-sky-300 text-sky-900 shadow-sky-100',
    gridRow: 4,
    gridCol: 0,
    arrowDirection: 'right',
  },
  {
    index: 6,
    label: '4',
    word: 'four',
    category: 'number',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-900 shadow-yellow-100',
    gridRow: 4,
    gridCol: 1,
    arrowDirection: 'right',
  },
  {
    index: 7,
    label: 'Bike',
    word: 'bike',
    category: 'toy',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-900 shadow-emerald-100',
    gridRow: 4,
    gridCol: 2,
    arrowDirection: 'right',
  },
  {
    index: 8,
    label: '7',
    word: 'seven',
    category: 'number',
    color: 'bg-orange-100 border-orange-300 text-orange-900 shadow-orange-100',
    gridRow: 4,
    gridCol: 3,
    arrowDirection: 'right',
  },
  {
    index: 9,
    label: 'Ruler',
    word: 'ruler',
    category: 'school',
    color: 'bg-fuchsia-100 border-fuchsia-300 text-fuchsia-900 shadow-fuchsia-100',
    gridRow: 4,
    gridCol: 4,
    arrowDirection: 'up',
  },
  {
    index: 10,
    label: '8',
    word: 'eight',
    category: 'number',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-900 shadow-indigo-100',
    gridRow: 3,
    gridCol: 4,
    arrowDirection: 'left',
  },
  {
    index: 11,
    label: 'Go-Kart',
    word: 'go-kart',
    category: 'toy',
    color: 'bg-rose-100 border-rose-300 text-rose-900 shadow-rose-100',
    gridRow: 3,
    gridCol: 3,
    arrowDirection: 'left',
  },
  {
    index: 12,
    label: 'Bag',
    word: 'bag',
    category: 'school',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-900 shadow-yellow-100',
    gridRow: 3,
    gridCol: 2,
    arrowDirection: 'left',
  },
  {
    index: 13,
    label: 'Pencil Case',
    word: 'pencil case',
    category: 'school',
    color: 'bg-fuchsia-100 border-fuchsia-300 text-fuchsia-900 shadow-fuchsia-100',
    gridRow: 3,
    gridCol: 1,
    arrowDirection: 'left',
  },
  {
    index: 14,
    label: 'Train',
    word: 'train',
    category: 'toy',
    color: 'bg-orange-100 border-orange-300 text-orange-900 shadow-orange-100',
    gridRow: 3,
    gridCol: 0,
    arrowDirection: 'up',
  },
  {
    index: 15,
    label: '6',
    word: 'six',
    category: 'number',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-900 shadow-emerald-100',
    gridRow: 2,
    gridCol: 0,
    arrowDirection: 'right',
  },
  {
    index: 16,
    label: 'Plane',
    word: 'plane',
    category: 'toy',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-900 shadow-indigo-100',
    gridRow: 2,
    gridCol: 1,
    arrowDirection: 'right',
  },
  {
    index: 17,
    label: 'Kite',
    word: 'kite',
    category: 'toy',
    color: 'bg-sky-100 border-sky-300 text-sky-900 shadow-sky-100',
    gridRow: 2,
    gridCol: 2,
    arrowDirection: 'right',
  },
  {
    index: 18,
    label: '5',
    word: 'five',
    category: 'number',
    color: 'bg-rose-100 border-rose-300 text-rose-900 shadow-rose-100',
    gridRow: 2,
    gridCol: 3,
    arrowDirection: 'right',
  },
  {
    index: 19,
    label: 'Monster',
    word: 'monster',
    category: 'toy',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-900 shadow-emerald-100',
    gridRow: 2,
    gridCol: 4,
    arrowDirection: 'up',
  },
  {
    index: 20,
    label: 'Pencil',
    word: 'pencil',
    category: 'school',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-900 shadow-emerald-100',
    gridRow: 1,
    gridCol: 4,
    arrowDirection: 'left',
  },
  {
    index: 21,
    label: 'Doll',
    word: 'doll',
    category: 'toy',
    color: 'bg-fuchsia-100 border-fuchsia-300 text-fuchsia-900 shadow-fuchsia-100',
    gridRow: 1,
    gridCol: 3,
    arrowDirection: 'left',
  },
  {
    index: 22,
    label: '3',
    word: 'three',
    category: 'number',
    color: 'bg-orange-100 border-orange-300 text-orange-900 shadow-orange-100',
    gridRow: 1,
    gridCol: 2,
    arrowDirection: 'left',
  },
  {
    index: 23,
    label: 'Car',
    word: 'car',
    category: 'toy',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-900 shadow-yellow-100',
    gridRow: 1,
    gridCol: 1,
    arrowDirection: 'left',
  },
  {
    index: 24,
    label: '2',
    word: 'two',
    category: 'number',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-900 shadow-indigo-100',
    gridRow: 1,
    gridCol: 0,
    arrowDirection: 'up',
  },
  {
    index: 25,
    label: 'Rubber',
    word: 'rubber',
    category: 'school',
    color: 'bg-sky-100 border-sky-300 text-sky-900 shadow-sky-100',
    gridRow: 0,
    gridCol: 0,
    arrowDirection: 'right',
  },
  {
    index: 26,
    label: '9',
    word: 'nine',
    category: 'number',
    color: 'bg-rose-100 border-rose-300 text-rose-900 shadow-rose-100',
    gridRow: 0,
    gridCol: 1,
    arrowDirection: 'right',
  },
  {
    index: 27,
    label: 'Notebook',
    word: 'notebook',
    category: 'school',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-900 shadow-emerald-100',
    gridRow: 0,
    gridCol: 2,
    arrowDirection: 'right',
  },
  {
    index: 28,
    label: 'Ball',
    word: 'ball',
    category: 'toy',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-900 shadow-yellow-100',
    gridRow: 0,
    gridCol: 3,
    arrowDirection: 'right',
  },
  {
    index: 29,
    label: 'Finish',
    word: 'finish',
    category: 'finish',
    color: 'bg-orange-500 border-orange-600 text-white shadow-orange-200',
    gridRow: 0,
    gridCol: 4,
  },
];
